# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f94a11acdbb636f33ed6ea7a0450c7b4312ae50836846b8a868d33a48b1568ebb745d18282d84db761b1640abc5447218bfcc376ba441d4b34c39c6b93a7fc55

test:
  secret_key_base: bc7c53314f84a189134476990051a8e5b37a0beef894b2bc08e3a7479ed68d977d670870b84901839b856a7a6ca67d99230192abe6603b1ea389ad5301c891e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
